### ISSUE TITLE
Why no objective c  SDK?

### ISSUE THREAD

**Issue by d9j** [pushy-me/pushy-demo-ios#2]
I just found that you have no sdk for objective c ..but only swift 3. the project written in legacy swift 2.3 and objective c.. due to time constraints and project size. + libraries I'm unable to migrate to swift 3.,. simply because your library is written in swift 3,. you should have provided either the objective c implementation or opensource sdk which I could use to port to objective c.

**Comment by pushy** [comment]
Hi @LinkedHK,
Thanks for your report.

Unfortunately, at this time we are unable to support Swift 2.3 due to the substantial syntax/class differences between Swift 2.3 and 3.0.

We hope that in the future, when you find the time to migrate your project to Swift 3.0, you will reconsider using Pushy again.

**Comment by d9j** [comment]
but at least there should be available  objective c sdk after all,. which is compatible with all versions of swift

**Comment by pushy** [comment]
Hi @LinkedHK,
You are absolutely right.

We have just updated our documentation, adding specific instructions for Objective C projects:
https://pushy.me/docs/ios/get-sdk

Thank you for the suggestion.

**Comment by rajazz** [comment]
Hi @pushy-me 

I'm not able to import Pushy SDK framework to my objective c project. Installed Cocoapod also. Still I'm not able to find the header. It always says Pushy module not found

**Comment by pushy** [comment]
HI @rajazz,
To avoid the error, please add a blank `.swift` file to your Xcode project. This file can be empty.
