### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by mharlowfod** [pushy-me/pushy-demo-ios#3]
Hello,

I've just been running into an issue where xcode keeps prompting me to covert pushy cocoapod to swift 5 (suggesting using the following code in 2 places: return (((try? get(key)) as String??)).flatMap { $0 }) but then cocoapods rolls it back down to swift 4.2 when I run 'pod update'.

Is there a Swift 5-compatible version of pushy yet?

My podfile is as follows for pushy:

`pod` 'Pushy', '1.0.18'

**Comment by pushy** [comment]
Hi @mharlowfod,
Thanks so much for bringing this to our attention.

We have just published version `1.0.20` which includes Swift 5.0 code migration (see this commit: https://github.com/pushy-me/pushy-sdk-ios/commit/68a3fad52b9d446d58ae67140b325e74ed02130d) to resolve this issue.

Please update your Podfile to reference the latest version and run `pod install` 🎉

**Comment by mharlowfod** [comment]
Thanks for the extremely quick turnaround! 2 for 2 recently (the first being iOS 13 push notification header)
