### ISSUE TITLE
UNUserNotificationCenter to detect notif tap

### ISSUE THREAD

**Issue by ganico** [pushy-me/pushy-demo-ios#4]
I can't see any implementation to get a way to detect the tapping of notification, any idea?

**Comment by pushy** [comment]
Hi @ganico,
Thanks for reaching out. We've taken your suggestion into consideration, and have released a new version of the SDK with a new method for subscribing to notification tap events.

1. Import version `1.0.31` of the [Pushy iOS SDK](https://pushy.me/docs/ios/get-sdk) by adding the following statement to your project's `Podfile` within the target declaration:

```
pod 'Pushy', '1.0.31'
```

2. Save the file and run the following command to install the new version:

```
pod install
```

3. Add the following code within the `didFinishLaunchingWithOptions` method of your `AppDelegate.swift`, after `pushy.setNotificationHandler()`, to listen for when the user taps your notifications:

```
// Handle notification tap event
pushy.setNotificationClickListener({ (data) in
    // Show an alert dialog
    let alert = UIAlertController(title: "Notification Click", message: data["message"] as? String, preferredStyle: UIAlertController.Style.alert)
    alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
    self.window?.rootViewController?.present(alert, animated: true, completion: nil)
    
    // Navigate the user to another page or
    // execute other logic on notification click
})
```

Run your app, send yourself a notification, and test whether tapping on it displays the relevant alert.

**Comment by ganico** [comment]
Thank you so much for your consideration, will apply it later. 🙏
